version: '3.5'

services:
  product-data:
    build: ./
    command: ./product-data
    hostname: productdata
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb
      - DB_USERNAME=root
      - DB_PASSWORD=qwerty
      - DB_DATABASE=admin
      - DB_COLLECTION=data
      - SERVER_HOST=productdata
      - SERVER_PORT=9000
      - CLIENT_TIMEOUT=300s
    networks:
      - product_data
  mongodb:
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=qwerty
      - MONGODB_DATABASE=admin
    ports:
      - "27017:27017"
    networks:
      - product_data

networks:
  product_data:
    name: data_network